// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw9p6PH-wyIzNrKmpSydCc8gvyro3H5ho',
    appId: '1:587982285191:android:0c2cce04f765149a934b22',
    messagingSenderId: '587982285191',
    projectId: 'shaghalny-a488f',
    storageBucket: 'shaghalny-a488f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1EtONcVy9EwYAXz4jNfALHg5mYBrbETg',
    appId: '1:587982285191:ios:774adc24fd12b393934b22',
    messagingSenderId: '587982285191',
    projectId: 'shaghalny-a488f',
    storageBucket: 'shaghalny-a488f.appspot.com',
    androidClientId: '587982285191-3ampour2977i8ivb0gobngv8uhtocn4e.apps.googleusercontent.com',
    iosClientId: '587982285191-0eqnatdtp8grom3g71ph1fphs9dad6o7.apps.googleusercontent.com',
    iosBundleId: 'com.sha8alny.shaghalny',
  );
}
